Fix Net undefined exception when generating client
Sources API Version: 1.0
rake aborted!
NameError: uninitialized constant Net
/home/agrare/src/topological_inventory/sources-api/lib/tasks/client_generate.rake:30:in `generator_cli_jar'
/home/agrare/src/topological_inventory/sources-api/lib/tasks/client_generate.rake:57:in `generate_client'
/home/agrare/src/topological_inventory/sources-api/lib/tasks/client_generate.rake:74:in `block (2 levels) in <top (required)>'
/home/agrare/.gem/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
Tasks: TOP => client:generate
(See full trace by running task with --trace)